name 'mukaibot-bamboo'
version '1.0.0'
source 'https://bitbucket.org/mukaibot/ds_bamboo/src'
author 'Timothy Mukaibo'
description 'Install Bamboo 5.5'
summary 'Downloads and installs Bamboo 5.5 with a Postgres backend'
license 'ASL 2.0'
project_page 'https://bitbucket.org/mukaibot/ds_bamboo'

dependency 'puppetlabs/postgresql'
